import 'package:get/get.dart';

class LocaleString extends Translations{
  @override
  // TODO: implement keys
  Map<String, Map<String, String>> get keys => {
    'en_US':{
      'Dashboard':'Dashboard',
      'Scheme':'Scheme',
      'Events':'Events',
      'Articles':'Articles',
      'Gallery':'Gallery',
      'Donation':'Donation',
      'Private Donation':'Private Donation',
      'Registration':'Registration',
      'changelang':'Change Language',
      'Home':'Home',
      'Search':'Search',
      'News Videos':'News Videos',
      'Shopping':'Shopping',
      'More':'More',
      '  Product Categories':'  Product Categories',
      '  Hot Products':'  Hot Products',
      '  New Arrival Products':'  New Arrival Products',
      'Welcome':'Welcome',
      'Follow':'Follow',
      'Message':'Message',
      'Latest Video':'Latest Video',
      'About Myconstituency':'About Mycontituency',
      'Notification':'Notification',
      'Profile':'Profile',
      'Videos':'Videos',
      'Login':'Login',
      'Logout':'Logout',
      'Complaint':'Complaint',
      'Myconstituency Fellowship':'Myconstituency Fellowship',
    },
    'hi_IN':{
      'Dashboard': 'डैशबोर्ड',
      'Scheme':'योजना',
      'Events':'आयोजन',
      'Articles':'सामग्री',
      'Gallery':'गेलरी',
      'Donation':'दान',
      'Private Donation':'निजी दान',
      'Registration':'पंजीकरण',
      'changelang':'भाषा बदलें',
      'Home':'होम',
      'Search':'खोज',
      'News Videos':'समाचार',
      'Shopping':'खरीदारी',
      'More':'अधिक',
      '  Product Categories':'  उत्पाद श्रेणियां',
      '  Hot Products':'  होट प्रोडक्टस',
      '  New Arrival Products':'  नये आगमन प्रोडक्टस',
      'Welcome':'स्वागत',
      'Follow':'अनुसरण',
      'Message':'संदेश',
      'Latest Video':'नवीनतम वीडियो',
      'About Myconstituency':'मायकॉन्सटीट्यूयन्सी के बारे में',
      'Notification':'अधिसूचना',
      'Profile':'प्रोफ़ाइल',
      'Videos':'वीडियो',
      'Login':'लॉग इन',
      'Logout':'लॉग आउट',
      'Complaint':'शिकायत',
      'Myconstituency Fellowship':'Myconstituency फेलोशिप',

    },
    'kn_IN':{
      'Dashboard': 'ಹಲೋ ವರ್ಲ್ಡ್',
      'Scheme':'ಯೋಜನೆ',
      'Events':'ಕಾರ್ಯಕ್ರಮಗಳು',
      'Articles':'ಲೇಖನಗಳು',
      'Gallery':'ಗ್ಯಾಲರಿ',
      'Donation':'ದೇಣಿಗೆಗಳು',
      'Private Donation':'ಖಾಸಗಿ ಕೊಡುಗೆ',
      'Registration':'ನೋಂದಣಿ',
      'changelang':'ಭಾಷೆ ಬದಲಾಯಿಸಿ',
      'Home':'ಮುಖಪುಟ',
      'Search':'ಹುಡುಕಿ',
      'News Videos':'ಸುದ್ದಿ ವೀಡಿಯೊಗಳು',
      'Shopping':'ಶಾಪಿಂಗ್',
      'More':'ಇನ್ನಷ್ಟು',
      '  Product Categories':'  ಉತ್ಪನ್ನ ವರ್ಗಗಳು',
      '  Hot Products':'  ಬಿಸಿ ಉತ್ಪನ್ನಗಳು',
      '  New Arrival Products':'  ಹೊಸ ಆಗಮನ ಉತ್ಪನ್ನಗಳು',
      'Welcome':'ಸ್ವಾಗತ',
      'Follow':'ಅನುಸರಿಸಿ',
      'Message':'ಸಂದೇಶ',
      'Latest Video':'ಇತ್ತೀಚಿನ ವೀಡಿಯೊ',
      'About Myconstituency':'ಬಗ್ಗೆ Mycontituency',
      'Notification':'ಅಧಿಸೂಚನೆ',
      'Profile':'ಪ್ರೊಫೈಲ್',
      'Videos':'ವೀಡಿಯೊಗಳು',
      'Login':'ಲಾಗಿನ್',
      'Logout':'ಲಾಗ್ ಔಟ್',
      'Complaint':'ದೂರು',
      'Myconstituency Fellowship':'Myconstituency ಫೆಲೋಶಿಪ್',
    }
  };

}