// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHJgRp-S-GtfgnZu89WmdsdW9vKeB5aWU',
    appId: '1:179905838866:web:9a845bc6fdb6e5c949bdcb',
    messagingSenderId: '179905838866',
    projectId: 'vchoice-b99ec',
    authDomain: 'vchoice-b99ec.firebaseapp.com',
    databaseURL: 'https://vchoice-b99ec-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'vchoice-b99ec.appspot.com',
    measurementId: 'G-EXFVF4J375',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGxacmdbLyVjtVzPeiL3eCkjV92yo7-gg',
    appId: '1:179905838866:android:897d195159e0d7a949bdcb',
    messagingSenderId: '179905838866',
    projectId: 'vchoice-b99ec',
    databaseURL: 'https://vchoice-b99ec-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'vchoice-b99ec.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiTPCEaPvoc-hWBkDVLE_xATFwSNrFmJA',
    appId: '1:179905838866:ios:2963569e02010db249bdcb',
    messagingSenderId: '179905838866',
    projectId: 'vchoice-b99ec',
    databaseURL: 'https://vchoice-b99ec-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'vchoice-b99ec.appspot.com',
    androidClientId: '179905838866-64pn4osltf5eliegcsgcgjvc5ugk2ikq.apps.googleusercontent.com',
    iosClientId: '179905838866-t3c22vier85tjgi5btmig2stl6ko2gj3.apps.googleusercontent.com',
    iosBundleId: 'com.example.vChoice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAiTPCEaPvoc-hWBkDVLE_xATFwSNrFmJA',
    appId: '1:179905838866:ios:2963569e02010db249bdcb',
    messagingSenderId: '179905838866',
    projectId: 'vchoice-b99ec',
    databaseURL: 'https://vchoice-b99ec-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'vchoice-b99ec.appspot.com',
    androidClientId: '179905838866-64pn4osltf5eliegcsgcgjvc5ugk2ikq.apps.googleusercontent.com',
    iosClientId: '179905838866-t3c22vier85tjgi5btmig2stl6ko2gj3.apps.googleusercontent.com',
    iosBundleId: 'com.example.vChoice',
  );
}
